# Generated by Django 4.2.3 on 2023-09-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=2)),
                ('style', models.IntegerField(choices=[(1, 'rap'), (2, 'pap')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MuzicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CenterApp.singermodel')),
            ],
        ),
    ]
