# Generated by Django 4.2.3 on 2023-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CenterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singermodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
